### ISSUE TITLE
ERROR in app: Exception on /create/eventarc/triggers [GET]

### ISSUE THREAD

**Issue by fbukevin** [iKala-Cloud/ops-event-generator#13]
When creating eventarc triggers with calling API `/create/eventarc/triggers`:

```shell
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/app/eventarc/trigger_creator.py", line 141, in create_eventarc_triggers data = get_eventarc_detail() File "/app/eventarc/trigger_creator.py", line 25, in get_eventarc_detail data = get_enabled_events(PROJECT_ID) File "/app/adminrun.py", line 21, in get_enabled_events result = response.json() File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json return complexjson.loads(self.text, **kwargs) File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads return _default_decoder.decode(s) File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by fbukevin** [comment]
Fixed in commit https://github.com/iKala-Cloud/ops-event-generator/commit/b2daf3031f97436bb6b575798c00c565a8fc0e6b
